version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    volumes:
      - ./resources/prometheus/jmx_prometheus_javaagent-0.16.1.jar:/usr/app/jmx_prometheus_javaagent.jar
      - ./resources/jmx-exporter/kafka-exporter.yml:/usr/app/kafka-exporter.yml
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://host.docker.internal:29092,LISTENER_DOCKER_EXTERNAL://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/kafka-exporter.yml

  kowl:
    image: quay.io/cloudhut/kowl:v1.4.0
    restart: on-failure
    hostname: kowl
    volumes:
      - ./resources/kowl/kowl-config.yaml:/etc/kowl/kowl-config.yaml
    ports:
      - "4040:4040"
    entrypoint: ./kowl --config.filepath=/etc/kowl/kowl-config.yaml
    depends_on:
      - kafka

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./resources/grafana:/var/lib/grafana
    depends_on:
      - prometheus

  maven-quarkus:
    image: maven
    volumes:
      - "./kafka-simple:/app"
      - "~/.m2:/root/.m2"
    environment:
      JAVA_OPTIONS: "-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
    depends_on:
      - kafka
    ports:
      - "8888:8888"
      - "5888:5888"
    working_dir: /app
    command: "./mvnw compile quarkus:dev -DdebugHost=0.0.0.0"